name: Deploy with CDK

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.1
        with:
          node-version: 14.x

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli

      - name: Install AWS CDK and dependencies
        run: |
          npm install -g aws-cdk
          npm install

      - name: Deploy_CDK_Stack
        run: |
          cdk deploy --require-approval never --outputs-file ./cdk-outputs.json

          echo "::set-output name=DISTRIBUTION_ID::$(
            cat cdk-outputs.json |
            grep distributionID |
            sed -n 's/.*"distributionID": *"\([^"]*\)".*/\1/p'
            )"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
      - name: Invalidate Cache
        with:
          DISTRIBUTION_ID: "${{ steps.Deploy_CDK_Stack.outputs.DISTRIBUTION_ID }}"
        run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID
